Migrate services from superduperdb to private
SuperDuperDB/superduperdb-staging pull request #5
Opened 2024-07-03 08:34 UTC by kartik4949

## Description

## Related Issues

## Checklist

- [ ] Is this code covered by new or existing unit tests or integration tests?
- [ ] Did you run `make unit_testing` and `make integration-testing` successfully?
- [ ] Do new classes, functions, methods and parameters all have docstrings?
- [ ] Were existing docstrings updated, if necessary?
- [ ] Was external documentation updated, if necessary?

## Additional Notes or Comments

2024-07-08 15:03 UTC, blythed requested changes
The workflows and `Makefile` will break with this. Please migrate also.

2024-07-08 21:02 UTC, blythed commented on .github/workflows/ci_code.yml
>            docker exec testenv-sandbox-1 sh -c 'make databackend_testing'
This is now only used for mongodb testing, the whole sandbox build, etc., is overkill. We should simplify.

2024-07-09 07:25 UTC, kartik4949 commented on .github/workflows/ci_code.yml
>            docker exec testenv-sandbox-1 sh -c 'make databackend_testing'
can we do it as separate pr? 
else the pr will be overloaded with big changes

2024-07-09 07:50 UTC, blythed approved these changes
Thanks!

2024-07-09 07:50 UTC, merged